### ISSUE TITLE
[REQUEST] Utilize "External Components" (for serial stream server and zeroconf) in ESPHome config

### ISSUE THREAD

**Issue by Hedda** [syssi/esphome-zb-gw03#1]
@syssi Suggest utilizing "External Components" (for serial stream server component and zeroconf component) in configuration.

External components feature was added in esphome 1.18

If you re-arrange your repo, the code can be pulled dynamically from the yaml.

Maybe add link to readme files for reference once adjust the repos -> https://esphome.io/components/external_components.html

This code repo has to have rearranged directories into like "components/esphome-stream-server" "components/zeroconf" so can be pulled dynamically from ESPHome yaml

oxan has done this in his repo for his "Stream server for ESPHome" -> https://github.com/oxan/esphome-stream-server

```
external_components:
  - source: github://oxan/esphome-stream-server

serial_server:
```

or if use esphome-serial-server from thegroove

```
external_components:
  - source: github://thegroove/esphome-serial-server

serial_server:
```

Same for Zeroconf if added

```
external_components:
  - source: github://thegroove/esphome-zeroconf

zeroconf:
```

PS: As an example can see how thegroove implemented external components in this experimental repo:

https://github.com/thegroove/esphome-zha-ezsp-zeroconf

**Comment by syssi** [comment]
This is already the case. What do you miss in detail? :-)
