### ISSUE TITLE
Could someone share working config with ethernet enabled?

### ISSUE THREAD

**Issue by ssolodennikov** [syssi/esphome-zb-gw03#28]
May be I missing something - could someone share working yaml with ethernet enabled?

**Comment by syssi** [comment]
This is a working YAML with ethernet enabled: https://github.com/syssi/esphome-zb-gw03/blob/main/coordinator-example.yaml

**Comment by ssolodennikov** [comment]
I am sorry, I just missed included YAMLs. Need to go to sleep earlier :)
