### ISSUE TITLE
ZB-GW03-V1.4

### ISSUE THREAD

**Issue by Slonik** [syssi/esphome-zb-gw03#30]
Is the current firmware suitable for version 1.4?
![IMG_20230915_155245](https://github.com/syssi/esphome-zb-gw03/assets/1193053/2a5e3c84-ec01-4784-aa9f-b332eb1a76ee)

**Comment by syssi** [comment]
Could you provide a photo of the upper side of the board. I would like to see / identify the different chips.

**Comment by syssi** [comment]
https://github.com/arendst/Tasmota/discussions/12764#discussioncomment-6340566

```
backlog template {"NAME":"ZHA-bridge","GPIO":[0,0,5472,0,5504,0,0,0,5793,5792,320,544,5536,0,5600,0,0,0,0,5568,0,0,0,0,0,0,0,0,608,640,32,0,0,0,0,0],"FLAG":0,"BASE":1} ; module 0
``` 

In general the hardware version should be suitable but it's untested and unverified yet.

**Comment by gdanov** [comment]
I have that version. Flashed esphome without any issues, ZB fw upload works, everything's great.

**Comment by lcavalli** [comment]
Confirmed v1.4 working also as zigbee proxy using provided instructions.
