### ISSUE TITLE
No ACK on EOT

### ISSUE THREAD

**Issue by medassi** [syssi/esphome-zb-gw03#45]
Hi,
After many attempts, I still encounter this error:
Xmodem sectors/kbytes sent: 1780/222k
Retry 0: No ACK on EOT
The upload fails before completion. I've tried with all the firmware versions, and the result is always the same.

I've updated the ESPHome layer to 2024.12.2, and HA recognizes it as ESPHome 2024.12.2, so that part seems fine.
The current Zigbee firmware is 6.7.10.0 build 423.
I need to update my ZB-GW03-1.4 gateway to make it Ember-compatible with HA.

What am I missing?

**Comment by syssi** [comment]
Could you tell me the exact filename and source of your zigbee firmware file? Why do you prefer version 6.7 over 7.4?

**Comment by medassi** [comment]
I don’t prefer version 6.7. I want version 7.4, but I have tested the others as well. The firmware file is from xsp1989.

**Comment by syssi** [comment]
Do you like to provide some more details? Which file did you use? I can offer to write the mentioned firmware to my device just for testing.

**Comment by medassi** [comment]
Ok thanks a lot. Here the firmware file : https://github.com/xsp1989/zigbeeFirmware/blob/master/firmware/ZigbeeBridge_SM-011-signed/ncp-uart-sw_7.4.3.0_115200.ota
I hope it's correct.

**Comment by syssi** [comment]
1. Turn on the "download mode" switch
2. Turn on the "zigbee reset" switch
3. Open a terminal an telnet into the bootloader and type `1<return>` to select the "upload gbl" option

![bootloader](https://github.com/user-attachments/assets/f310a8c7-3f42-43c4-8e04-ff642dbff444)

4. Don't close the telnet session. Go to a second terminal and start the upload:

![sx](https://github.com/user-attachments/assets/e01f57f7-f3f2-4eae-a136-a516f28797a8)

It's working fine on my device.

**Comment by medassi** [comment]
Ok thank you for this test. That doesn't reassure me. I do exactly the same thing but it doesn't happen the same. the upload runs correctly up to 222k and then stops, informing me that the upload is incomplete. I don't see where the error comes from at all. My gateway comes from Ali express and is stamped zb-gw-03 v1.4. On the other hand, it is not noted SM-011 on the chipset. Thanks anyway, I'll keep looking.

**Comment by medassi** [comment]
![image](https://github.com/user-attachments/assets/87998107-382b-4940-8bf4-83c8d0826004)

**Comment by syssi** [comment]
May be the Zigbee module rejects the new firmware for unknown reason. Which debian / lrzsz version do you use?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
$ dpkg -l | grep lrzsz
ii  lrzsz                                                       0.12.21-10+b1                                                              amd64        Tools for zmodem/xmodem/ymodem file transfer
$
```

**Comment by medassi** [comment]
![image](https://github.com/user-attachments/assets/d629c3d7-bfc2-40d2-9052-bd5fb178c5c5)
It seems that we have the same versions though.

**Comment by syssi** [comment]
Let's compare the versions of the Gecko Bootloader as next step. Could you telnet into your bootloader another time and have a look?

**Comment by medassi** [comment]
Yes of course, but it's the same as your :
![image](https://github.com/user-attachments/assets/5f859c1a-66c8-44e0-9978-0efdc179c62c)

**Comment by medassi** [comment]
oops !!! I'm really, really sorry for wasting your time. Everything works. I was using a simple wget to recover the ota file and I had to recover a corrupted file. I just redownloaded it directly from the github repository and sent it with winscp to my server. And there, the sx worked. Once again, sorry and many thanks for your perseverance. The bug is still between the chair and the keyboard...
![image](https://github.com/user-attachments/assets/329ccb7a-3433-4648-ac23-2eba9c259ba4)

**Comment by medassi** [comment]
All seems to be ok 👍 
![image](https://github.com/user-attachments/assets/733bb1a3-935d-4dcc-8027-bb26ab75d9c3)

**Comment by syssi** [comment]
Awesome! No problem. I'm happy you was able to resolve the issue. Merry christmas!

**Comment by syssi** [comment]
> wget https://github.com/xsp1989/zigbeeFirmware/blob/master/firmware/ZigbeeBridge_SM-011-signed/ncp-uart-sw_7.4.3.0_115200.ota

This doesn't work. Please check the content of the `ncp-uart-sw_7.4.3.0_115200.ota` file. I guess it's HTML.

This command should download the binary file:

```
wget https://github.com/xsp1989/zigbeeFirmware/raw/refs/heads/master/firmware/ZigbeeBridge_SM-011-signed/ncp-uart-sw_7.4.3.0_115200.ota
```

**Comment by ElVit** [comment]
Thank you, this was the problem. Now its working 😃
